const FlowType = Object.freeze({
  JOB: "JOB",
  GENERAL_EXPENSES: "GENERAL_EXPENSES",
  BIRTH_CHILD: "BIRTH_CHILD",
  RECEIVING_SALARY: "RECEIVING_SALARY",
  CASH: "CASH",
  STOCK_FUND_METAL_INDUSTRY: "STOCK_FUND_METAL_INDUSTRY",
  SALE_BUSINESS: "SALE_BUSINESS",
  SALE_HOUSE: "SALE_HOUSE"
});

export default FlowType;
